version: '3.8'

services:
  next-launch-kit:
    image: postgres:14
    container_name: next-launch-kit
    environment:
      POSTGRES_USER: next-launch-kit-user
      POSTGRES_PASSWORD: next-launch-kit-password
      POSTGRES_DB: next-launch-kit-db
    ports:
      - '5432:5432'
    volumes:
      - next-launch-kit-data:/var/lib/postgresql/data

volumes:
  next-launch-kit-data:
